language: bash

os:
  - linux
  - osx

script:
  - export SHELL="/bin/bash" && curl -L https://raw.githubusercontent.com/jackdoe/juun/master/download-and-install.sh | bash
  - export SHELL="/bin/zsh" && curl -L https://raw.githubusercontent.com/jackdoe/juun/master/download-and-install.sh | bash

